services:
  backup-manager:
    build: .
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - BUCKET_NAME=${BUCKET_NAME}
      - FOLDERS_TO_BACKUP=${FOLDERS_TO_BACKUP}
      - BACKUP_MOUNT=${BACKUP_MOUNT}
    env_file:
      - .env
    volumes:
      - /home/tbe/Desktop/:${BACKUP_MOUNT}/Desktop:ro
      - /home/tbe/Pictures/:${BACKUP_MOUNT}/Pictures:ro
      - ${GOOGLE_APPLICATION_CREDENTIALS}:${GOOGLE_APPLICATION_CREDENTIALS}:ro
    command: python backup-manager/main.py
